# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
          
      - name: Remove Allure result files
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./allure-results
          
      - name: Cypress run in Chrome
        uses: cypress-io/github-action@v2.9.7
        with:
          browser: chrome
        continue-on-error: true
      
      - name: Generate Allure report
        run: npm run allure:report
        
      - name: Deploy report to GitHub pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
